### ISSUE TITLE
Ability to paste an IP address into direct connect

### ISSUE THREAD

**Issue by janosharsanyi** [danielknobe/blobbyvolley2#12]
Currently it's not possible to paste an IP address into the direct connect textbox, so it must be typed manually.

Alternatively there could be a command line option for the client to start in direct connect mode and connect to the given server.
For example: `./blobby --connect <server-ip>`

**Comment by danielknobe** [comment]
Thanks for that issue.
This feature can be very helpful for a lot of users. Added a simple implementation with 2b452b1 for ASCII only characters for the editbox component so that every text input has paste feature (ctrl + v) now. A command line option is not planned.

Please close issue if that is what you expected.

**Comment by janosharsanyi** [comment]
Thanks, nice. I wasn't sure which was easier to implement.
